# This is a basic workflow to help you get started with Actions

name: JS Actions
on:
  pull_request:
    types: [labeled]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: hello-action
        uses: ./.github/actions/hello-world
      - name: some-jokes
        uses: ./.github/actions/joke-action
